-- Insert sample customer records
INSERT INTO customers (first_name,
                       last_name,
                       email,
                       phone,
                       street_address,
                       city,
                       province,
                       postal_code,
                       country,
                       date_of_birth,
                       preferred_contact)
VALUES ('John',
        'Smith',
        'john.smith@email.com',
        '5551234567',
        '123 Main St',
        'Austin',
        'Texas',
        '78701',
        'United States',
        '1985-06-15',
        'email'),
       ('Maria',
        'Garcia',
        'maria.garcia@email.com',
        '5559876543',
        '456 Oak Avenue',
        'San Antonio',
        'Texas',
        '78205',
        'United States',
        '1990-03-22',
        'phone'),
       ('Robert',
        'Johnson',
        'robert.johnson@email.com',
        '5554567890',
        '789 Pine Road',
        'Houston',
        'Texas',
        '77001',
        'United States',
        '1982-11-30',
        'mail');
