-- Insert sample order data
INSERT INTO orders (customer_id,
                    order_number,
                    shipping_address,
                    shipping_city,
                    shipping_state,
                    shipping_postal_code,
                    shipping_method,
                    payment_method,
                    subtotal,
                    shipping_cost,
                    tax_amount,
                    total_amount,
                    order_status,
                    payment_status)
VALUES (1, -- John Smith
        'ORD-2024-001',
        '123 Main St',
        'Austin',
        'Texas',
        '78701',
        'Standard Shipping',
        'Credit Card',
        999.99,
        9.99,
        82.50,
        1092.48,
        'delivered',
        'completed');